### PR TITLE
fix(desktop): upgrade FileKit to 0.13 for dbus-java 5.2 compatibility

### PR DESCRIPTION
**Pull request by W-Nana**
## Summary

- Upgrade FileKit from `0.10.0-beta04` to `0.13.0` so Linux XDG file pickers work with `dbus-java` 5.2.0.
- Migrate FileKit dialog APIs: drop removed `title` parameter on `rememberFilePickerLauncher`, pass directory chooser title via `FileKitDialogSettings`.

## Problem

On Linux, Settings → Account → Upload Avatar → Select File crashed with:

```text
java.lang.NoSuchMethodError:
  'java.lang.AutoCloseable
   org.freedesktop.dbus.connections.impl.DBusConnection.addGenericSigHandler(...)'
```

## Root cause

FileKit `0.10.0-beta04` was built against dbus-java ​**5.1.x**​, while animeko pulls dbus-java **5.2.0** (screen-saver inhibit). The binary signature of `addGenericSigHandler` changed, so the XDG portal picker failed after portal version probing. Matches upstream [FileKit#476](https://github.com/vinceglb/FileKit/issues/476).

## Changes

* `gradle/libs.versions.toml`: `filekit = "0.13.0"`
* `ProfileGroup.kt`: remove unsupported `title` argument
* `CacheDirectoryGroup.desktop.kt`: use `FileKitDialogSettings(title = ...)`

### CODE REVIEW

File: gradle/libs.versions.toml [hunk 1]
```diff
@@ -57,7 +57,7 @@ jna = "5.13.0" # 不要轻易改这个版本, 它可能导致 VLC 兼容性问
 dbus-java = "5.2.0"
 jsonpathkt-kotlinx = "3.0.2"
 ksoup = "0.2.2"
-filekit = "0.10.0-beta04" # https://github.com/vinceglb/FileKit/releases
+filekit = "0.13.0" # https://github.com/vinceglb/FileKit/releases
```
[the remark this answers is not in the document]
Comment (NihilDigit) [reply gradle/libs.versions.toml:60]: FileKit 0.13.0 transitively requests jna and jna-platform 5.18.1, so Gradle upgrades the desktop runtime from the repository’s intended JNA 5.13.0. The existing version catalog entry is not an actual pin.
Please explicitly force both JNA artifacts to libs.versions.jna when upgrading FileKit:

```kotlin
subprojects {
    configurations.configureEach {
        resolutionStrategy.force(
            "net.java.dev.jna:jna:${libs.versions.jna.get()}",
            "net.java.dev.jna:jna-platform:${libs.versions.jna.get()}",
        )
    }
}
```

I verified this combination on Linux: the desktop build succeeds, the XDG avatar file picker opens and returns a selected file, and VLC playback works without JNA/DBus linkage errors.

**Review by NihilDigit — CHANGES_REQUESTED** [review]

**Review by NihilDigit — APPROVED** [review]

**Comment by NihilDigit** [comment]
Thanks for the fix and for addressing the review feedback! I’ve enabled auto-merge, so this will merge once CI passes.
